<a href="https://colab.research.google.com/github/Sopiaa2/daily_project_test/blob/main/Untitled1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
##pandas 와 numpy를 파이썬에서 불러오다.
import pandas as pd
import numpy as np


##구글 드라이브 연동 하려면 꼭 해야함!
from google.colab import drive
drive.mount('/content/drive')

##연동하는데 엄청 걸렸다 ㅠㅠ ...... 네이버에 주피터 관련 블로그 글이 너무 많아서 다 따라해봤는데 실질적으로 코랩에 구글드라이브를 연동해서 써야하는 방법이 따로 있었다. 2시간 까먹은듯.

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [34]:
##구글 드라이브 연동 되었으면 -> 화면 상단에 [파일] -> [구글 드라이브에서 찾기]

data_frame = '/content/drive/MyDrive/Colab Notebooks/KSY.csv'  
##파일찾아서 경로복사



##read - ?   /  encoding - 한글 패치
pd.read_csv(data_frame, encoding='cp949')

    날짜    김    승    열
0  1.0    정    인    지
1  2.0   홍    길     동
2  3.0    공   룡     뼈
3  4.0   치    킨     무
4  NaN  NaN  NaN  NaN
5  NaN  NaN  NaN  NaN
6  NaN  NaN  NaN  NaN
7  NaN  NaN  NaN  NaN
8  NaN  NaN  NaN  NaN

**google colab의 단점**
1. 최대 세션 유지시간은 12시간
즉, 딥러닝의 세션이 12시간을 초과해서 걸린다고 하면 중간에 자동으로 연결 끊김.
2. 세션이 만료되면 학습중, 저장되어있는 데이터 소멸함.

그래서 google colab 이 pro를 사용하게 만들어놨다.
- 더 좋은 cpu
- 고용량 RAM 사용가능
- 더 긴 런타임

사람들이 우회해서 쓰는 방법(비용무료)
 - 크롬 브라우저 창 => F12(개발자 도구) => console